version: '3.8'
services:
  web:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - db
      - db1
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: Promo456
      MYSQL_DATABASE: hh_resume
    ports:
      - "3306:3306"
  db1:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: Promo456
      MYSQL_DATABASE: hh_vacancies2
    ports:
      - "3307:3307"
